Introduction to Python
================================

Lesson 2 - Part1
--------

## Summary

In this Lesson we will start using Python in order to create some models.

The models that we will create are:
  - Linear

In order to do so we must intruduce some important libraries:

  - Pandas
  - Sklearn
  - Numpy

In [1]:
%load_ext rpy2.ipython

## Numpy

Citing from the [Numpy Website](http://www.numpy.org/) :NumPy is the fundamental package for scientific computing with Python. It contains among other things:
  - a powerful N-dimensional array object
  - sophisticated (broadcasting) functions
  - tools for integrating C/C++ and Fortran code
  - useful linear algebra, Fourier transform, and random number capabilities
Fior the moment our focus is on the first point, in oder to start usign proper arrays.

In [3]:
import numpy as np
#Creation of an array
ar1=np.array([1,2,3])
print('type di ar1',type(ar1))
ar1

type di ar1 <class 'numpy.ndarray'>


array([1, 2, 3])

In [4]:
#Use shape to see the dimension of ar1
print('Dimension of ar1 are:',ar1.shape)
try:
    print('Using .shape()')
    print(ar1,ar1.shape())
except Exception as e:
    print('ERROR:',e)
    print('You must use .shape without brackets')
    print(ar1,ar1.shape)

Dimension of ar1 are: (3,)
Using .shape()
ERROR: 'tuple' object is not callable
You must use .shape without brackets
[1 2 3] (3,)


In [5]:
#Creation of a multimensional array
ar2=np.array([[1,2,3],[4,5,6]])#,dtype=complex
print('Shape di ar2',ar2.shape)
print(ar2)
len(ar2)

Shape di ar2 (2, 3)
[[1 2 3]
 [4 5 6]]


2

**NOTE**: array and matrix in nupy are different objects

In [6]:
#Creatiomn of a matrix
mt=np.mat('1 2;3 4')
print(type(mt),mt)
#Putting the matrix inside an array
ar3=np.array(np.mat('1 2; 3 4'))
print(type(ar3),ar3)
#In order to keep the correct type
ar3=np.array(np.mat('1 2; 3 4'), subok=True)
print(type(ar3),ar3)
ar3
# mt
ar2[1,]

<class 'numpy.matrixlib.defmatrix.matrix'> [[1 2]
 [3 4]]
<class 'numpy.ndarray'> [[1 2]
 [3 4]]
<class 'numpy.matrixlib.defmatrix.matrix'> [[1 2]
 [3 4]]


array([4, 5, 6])

**NOTE**: as we have seen in the previos lesson, also with `np.appay` we have to use `.copy()`.

Without `.copy()` we'll create a pointer to the original array.

In [7]:
print(ar2)
ar2_bis=ar2#.copy()
ar2_bis[1,]=[1,1,1]
print(ar2)
ar2_bis

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [1 1 1]]


array([[1, 2, 3],
       [1, 1, 1]])

## Other properties of np.array

Just to mention some other features, we can look to append:

In [8]:
ap1=np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]])
print(ap1,type(ap1))
#Please note that the result is flattened
ap2=np.append([[1, 2, 3]], [[4, 5, 6], [7, 8, 9]], axis=0)
print(ap2,type(ap2))
ap3=np.append([[1, 2, 3],[1,1,1]], [[4, 5, 6], [7, 8, 9]], axis=1)
print(ap3,type(ap3))

[1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>
[[1 2 3 4 5 6]
 [1 1 1 7 8 9]] <class 'numpy.ndarray'>


## Comparison between array an list

Let's understand why for big data it's important to use an array istead of a list.

We are going to do the sum of the list and two array. In one case is the sum of number, in the other the sum between two arrays like in linear algebra.

In [9]:
a=[i for i in range(0,10000)]
%timeit -n 100 s=a+a
b=np.array([i for i in range(0,10000)])
%timeit -n 100 s2=b+b

54.4 µs ± 3.74 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
The slowest run took 5.55 times longer than the fastest. This could mean that an intermediate result is being cached.
7.67 µs ± 6.69 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [10]:
%%R
c=as.integer(seq(1,10))
print(class(c))
d=data.frame(c)
print(class(d))

[1] "integer"
[1] "data.frame"


In [11]:
%%timeit -n 100
%R c+c

1.6 ms ± 277 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [12]:
%%timeit -n 100
%R d+d

2.26 ms ± 158 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## Pandas 

Citing the [Pandas Website](https://pandas.pydata.org/): *pandas is an open source, BSD-licensed library providing high-performance, easy-to-use data structures and data analysis tools for the Python programming language*.

What interest us the most is the possibility of create and use, like in R, **dataframes** ([Pandas DataFrame](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.html)).

In [13]:
import pandas as pd

#Creation of a dataframe
df=pd.DataFrame({'a':[1,2,3],'b':[4,5,6]})
print(df,'\n',type(df))
print('We can add columns afterward')
df['c']=[0,0,0]
print(df)
#Creatiion of a dataframe with index
df2 = pd.DataFrame([[1, 2], [4, 5], [7, 8]],
                  index=['cobra', 'viper', 'sidewinder'],
                  columns=['max_speed', 'shield'])
print(df2)
print(type(df2))
df3=pd.DataFrame({'col1':[10,20,30],'col2':['y','z','k']},index=['a','b','c'])
df3

   a  b
0  1  4
1  2  5
2  3  6 
 <class 'pandas.core.frame.DataFrame'>
We can add columns afterward
   a  b  c
0  1  4  0
1  2  5  0
2  3  6  0
            max_speed  shield
cobra               1       2
viper               4       5
sidewinder          7       8
<class 'pandas.core.frame.DataFrame'>


**NOTE**: a dataframe can be created also starting from a `np.array` simply using `pd.DataFrame`.

In [14]:
dfFromArray=pd.DataFrame(ap2)#,columns=['pippo','pluto','paperino'])
dfFromArray

## Properties of a dataframe

In the followig cell there is a sample of attributes ad properties of a pandas dataframe.

Some of them are:

  - `index`
  - `values`
  - `max()`
  - `add()`

In [15]:
%qtconsole
print(df)
df.index
df.values
df.columns()
df.max()
df.min()
df.mean()
df.median()
df.add(df)
#se the link above

   a  b  c
0  1  4  0
1  2  5  0
2  3  6  0


## Display dataframes nicely

In order to print a dataframe in a nice way, like it is visualized without print if it is at the of a cell, we can use `display` from the library `IPython.display`.

It is also possible to convert a dataframe to html with `to_html`, from the same library, and then use display.

**NOTE**: display can also print text before and after am object, just like `print`.

In [21]:
from IPython.display import display, HTML
display(df)
#Alternative
print('using .to_html()')
display(HTML(df.to_html()))
print('Display can also print text')
display('Some random text',df)

using .to_html()


Display can also print text


'Some random text'

## How to select row and columns

Let's dive a little bit more in some dataframes property.

Important functions for selecting dataframe's elements are:
  - `index` 
  - `loc`
  - `iloc`
 
The difference between `loc` and `iloc` is subtle
`loc` allow to select elemets by **name**
`iloc` allow to select elemets by **position**

It always possible to select columns by name with `[[]]`.

In [22]:
#Creation of a dataframe without an index
dfCity=pd.DataFrame({'val1':[10,20,30],'val2':[-1,-2,-3],'city':['Roma','Milano','Napoli']})
print('dfCity before the cration of the index')
display(dfCity)
#Selecting one column as index
dfCity.set_index('city')#inplace
display(dfCity)

dfCity before the cration of the index


In [25]:
#Selecting column by name
display(df)
print('Selection of a column by name')
display(df[['a']])
print('Selectig using loc')
display(df.loc[1])
#Select column by position
print('Print of the second colum')
display(df.iloc[:,1])

Selection of a column by name


Selectig using loc


a    2
b    5
c    0
Name: 1, dtype: int64

Print of the second colum


0    4
1    5
2    6
Name: b, dtype: int64

Let's focus a little bit on the difference between `loc` and `iloc`:

In [26]:
display(df2)
display('selection of cobra',df2.loc['cobra'])
display('Selection of row and column with loc',df2.loc['cobra','max_speed'])
display('Selection of row and column with iloc',df2.iloc[0,0])

'selection of cobra'

max_speed    1
shield       2
Name: cobra, dtype: int64

'Selection of row and column with loc'

1

'Selection of row and column with iloc'

1

**NOTE**: In both cases we can use a list to select multiple rows/columns or `:` to select a range

In [30]:
display('Row cobra, all cols',df2.loc['cobra',:])
display('Rows cobra and sidewinder, columns max speed',df2.loc[['cobra','sidewinder'],'max_speed'])
display('Using iloc',df2.iloc[0:2,0])
#NOTE 0:i i is excluded

'Row cobra, all cols'

max_speed    1
shield       2
Name: cobra, dtype: int64

'Rows cobra and sidewinder, columns max speed'

cobra         1
sidewinder    7
Name: max_speed, dtype: int64

'Using iloc'

cobra    1
viper    4
Name: max_speed, dtype: int64

In [31]:
display(df)
display('Selection with loc',df.loc[0])
display('Selection with iloc',df.iloc[0])
#Change of index
df.index=[1,2,0]
print('df after the change of the index:')
display(df)
display('loc:',df.loc[0],'iloc',df.iloc[0])

'Selection with loc'

a    1
b    4
c    0
Name: 0, dtype: int64

'Selection with iloc'

a    1
b    4
c    0
Name: 0, dtype: int64

df after the change of the index:


'loc:'

a    3
b    6
c    0
Name: 0, dtype: int64

'iloc'

a    1
b    4
c    0
Name: 1, dtype: int64

## Warning

If during the selection the dataframes number of columns is **1**, the type of the object changes from `pd.DataFrame` to `pandas.core.series.Series`. 
This is valid also if you have 2 colum but one **is the index**.

In [32]:
print('Original type',type(df2))
print('Only index',type(df2.set_index('max_speed')))
print('Only selection',type(df2.iloc[:,0]))
print('Index and select',type(df2.set_index('max_speed').iloc[:,0]))
display(df2.set_index('max_speed').iloc[:,0])

Original type <class 'pandas.core.frame.DataFrame'>
Only index <class 'pandas.core.frame.DataFrame'>
Only selection <class 'pandas.core.series.Series'>
Index and select <class 'pandas.core.series.Series'>


max_speed
1    2
4    5
7    8
Name: shield, dtype: int64

## Drop and other suff

After the selction of columns and rows let's focus on how to `drop` a column (aka selct out) from a dataframe.


In [48]:
#Let's drop c from df
df=pd.DataFrame({'a':[1,2,3],'b':[4,5,6],'c':[0,0,0]})
df.drop(['c'],axis=1)
display('df after the drop of c',df)
df.drop(columns=['b'],inplace=True)
display('df after the drop of b',df)
df.columns=['aaa','ccc']
display(df)
#We can also drop rows
df['nomi']=['pippo','pluto','topolino']
df.set_index(['nomi'],inplace=True)
display('df after the index definitio',df)
display('df after the drop of the row with label pluto',df.drop(['pluto'],axis=0))

'df after the drop of c'

'df after the drop of b'

'df after the index definitio'

'df after the drop of the row with label 2'

In [50]:
dfNan=pd.DataFrame([[1,np.nan,'pippo'],[2,'b','pluto'],[3,'c','topolino'],[np.nan,np.nan,'minnie']])
dict2Print={'orig':dfNan,'nothing':dfNan.dropna(),
            'axis=0':dfNan.dropna(axis=0),
            'axis=1':dfNan.dropna(axis=1),
           'how=any':dfNan.dropna(how='any'),
           'how=all':dfNan.dropna(how='all')}
for curConf,curDF in dict2Print.items():
    print('dropna with %s'%curConf)
    display(curDF)

dropna with orig


dropna with nothing


dropna with axis=0


dropna with axis=1


dropna with how=any


dropna with how=all


## Join of dataframes

A very handy function to use on dataframe is `join()`.

With join it is possible to combine different dataframe using one column as a key.

This function can be found also in R using `dplyr`.

In [51]:
dfLeft=pd.DataFrame({'key':['a','b','d','f'],'cost':[1,2,3,4]})
dfRight=pd.DataFrame({'key':['a','b','c','f'],'revenue':[10,20,30,40]})
display(dfLeft.join(dfRight))#lsuffix='_l',rsuffix='_r'
dfRight.set_index('key',inplace=True)
display(dfLeft.join(dfRight,on='key'))
#ALternative
dfLeft.set_index('key').join(dfRight)#how
howTypes=['left','right','inner','outer']
d={'how':'','other':dfRight}
for curType in howTypes:
    print('how:{}'.format(curType))
    d['how']=curType
    display(dfLeft.set_index('key').join(**d))

ValueError: columns overlap but no suffix specified: Index(['key'], dtype='object')

## Join in R

Just to make a conmparison we are going to make the same join in R.

To do this we'll use the possibility of using a dataframe creted with Pandas in a Python cell inside an R cell.

This is done by `magic` and the command is `%%R -i nameofthePythonDatframe` 

In [52]:
#First we have to remove the index from dfRight
dfRight.reset_index()

In [53]:
%%R -i dfLeft,dfRight
library(dplyr)
dfLeft %>%
    inner_join(dfRight,by='key')

/anaconda3/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:145: RRuntimeWarning: 
Attaching package: ‘dplyr’


  warnings.warn(x, RRuntimeWarning)
/anaconda3/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:145: RRuntimeWarning: The following objects are masked from ‘package:stats’:

    filter, lag


  warnings.warn(x, RRuntimeWarning)
/anaconda3/lib/python3.6/site-packages/rpy2/rinterface/__init__.py:145: RRuntimeWarning: The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


  warnings.warn(x, RRuntimeWarning)


  key cost revenue
1   a    1      10
2   b    2      20
3   f    4      40


## Exercise

You have to:

  - Create an `np.array` with **3** columns and **4** rows and ranform it in an `pd.dataFrame`. Value and column's names must be like the table below  
  - Create a first datafreme with columns **key** and **col1** and the **first** 3 rows
  - Create a first datafreme with columns **key** and **col2** and the **last** 3 rows
  - Join the two dataframes on key in **inner** mode
  - Drop one column of the result dataframe
  
| key | col1 | col2 |
|---|:-:|----|
| a | 1 | 10 |
| b | 2 | 20 |
| c | 3 | 30 |
| b | 4 | 40 |
| c | 5 | 50 |
| d | 6 | 60 |